---
- hosts: main
  vars_files:
    - vars.yml
    - vars.credentials.yml
  tasks:
    - file: dest=/root/db/mongo/data state=directory
    - file: dest=/root/db/redis/data state=directory
    - copy:
        dest: /root/db/docker-compose.yml
        content: |
          version: '2'
          services:
            mongodb:
              image: mongo:3.2
              restart: always
              volumes:
                - ./mongo/data:/data/db
            redis:
              image: redis:3.2
              restart: always
              volumes:
                - ./redis/data:/data
    - docker_service:
        project_src: /root/db/
        state: present
