version: '2'

volumes:
   pgdb:

services:
  redis:
    image: redis


  postgres:
    image: 'eeacms/postgres:9.5'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: sentry
      POSTGRES_DBUSER: sentry
      POSTGRES_DBPASS: sentry
    volumes:
     - pgdb:/var/lib/postgresql/data

  sentry:
    image: sentry:latest
    depends_on:
     - redis
     - postgres
    links:
     - redis
     - postgres
    ports:
     - 9000:9000
    environment:
      SENTRY_SECRET_KEY: verysecret
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis

  sentry_celery_beat:
    image: sentry:latest
    depends_on:
     - redis
     - postgres
    command: "sentry celery beat --pidfile=/tmp/celerybeat-sentry.pid"
    environment:
      SENTRY_SECRET_KEY: verysecret
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis

  sentry_celery_worker:
    image: sentry:latest
    depends_on:
     - redis
     - postgres
    command: "sentry celery worker"
    environment:
      SENTRY_SECRET_KEY: verysecret
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: postgres
      SENTRY_DB_PASSWORD: postgres
      SENTRY_REDIS_HOST: redis
